### ISSUE TITLE
Config file support.

### ISSUE THREAD

**Issue by domdfcoding** [repo-helper/simple503#10]
`simple503` could support per-repository configuration files which store the base URL (e.g. `/simple/`), whether to move the files, etc. The file can be in a known location relative to ``ORIGIN``, such as `simple503.toml`, and can be detected automatically. 

Command line options should take precedence over the config file, and the user should be able to pass a custom config filename as a CLI argument.

For example:

```toml

[simple503]
base-url = "/simple/"
sort = true
copy = true
# target = "./simple/"
```
